name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Run nsis
        run: makensis /LICENSE
      - name: install nsis
        run: |
          curl -O -L https://downloads.sourceforge.net/project/nsis/NSIS%203/3.06.1/nsis-3.06.1-setup.exe
          ./nsis-3.06.1-setup.exe /S
